### ISSUE TITLE
Expected User object. Got Array while adding siblings.

### ISSUE THREAD

**Issue by mukeshsinghr** [masciugo/genealogy#19]
I am trying to use `add_siblings(*siblings)` method to add more then one sibling at a time. I am giving array of users and I am getting above error.
`user.add_siblings([user1, user2,..])`

Whereas If I pass objects comma separated its working fine.
`user.add_siblings(user1, user2,..)`
As per [API document](https://www.rubydoc.info/github/masciugo/genealogy/master/Genealogy/AlterMethods#add_siblings-instance_method) it should work.

For more details Please check the below stacktrace.

` ["/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/util_methods.rb:175:in `check_indiv'", "/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/util_methods.rb:162:in `block in check_incompatible_relationship'", "/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/util_methods.rb:159:in `each'", "/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/util_methods.rb:159:in `check_incompatible_relationship'", "/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/alter_methods.rb:184:in `add_siblings'", "/home/mukesh/.rvm/gems/ruby-2.5.1@go-server/gems/genealogy-2.5.1/lib/genealogy/alter_methods.rb:211:in `add_sibling'",

`

**Comment by masciugo** [comment]
you should use comma separated User objects. 

So either:
`user.add_siblings(*[user1, user2,..])`
or
`user.add_siblings(user1, user2,..)`
